FROM maven:3.8.5-jdk-11-slim

COPY . /app

WORKDIR /app

RUN mkdir -p /odeyalo/dev/microservices/auth/qrcodes/

CMD mvn -s .github/workflows/maven-settings.xml -U install --file pom.xml -DQR_CODE_SAVING_PATH=${QR_CODE_SAVING_PATH} -DPOSTGRES_DATABASE_USERNAME=${POSTGRES_USER} -DPOSTGRES_DATABASE_PASSWORD=${POSTGRES_PASSWORD} -DPOSTGRES_DATABASE_CONNECTION_URL=${POSTGRES_DATABASE_CONNECTION_URL}

