name: file-storage
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: current directory
      - name: Build docker images
        run: docker build -t auth-microservice-image -f .github/Dockerfile.test .
      - name: Build docker compose
        run: docker-compose -f ${GITHUB_WORKSPACE}/.github/docker-compose.test.yml up --abort-on-container-exit
