name: file-storage
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker compose
        run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
      - uses: actions/checkout
      - uses: justJavaProgrammer/ci-telegram-bot-sender@v1.0
        with:
          repository-name: Aboba

